# Generated by Django 4.1.1 on 2022-09-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="github_username",
            field=models.CharField(default="dan1229", max_length=255),
            preserve_default=False,
        ),
    ]
