# Generated by Django 4.1.1 on 2022-09-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookreceived",
            name="sender",
            field=models.CharField(
                default="github", help_text="The sender of the event.", max_length=255
            ),
            preserve_default=False,
        ),
    ]
