# Generated by Django 4.1.1 on 2022-09-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_webhookreceived_sender"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubWebhookReceived",
            fields=[
                (
                    "webhookreceived_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webhooks.webhookreceived",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="The action of the event.", max_length=255
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(help_text="The type of webhook.", max_length=255),
                ),
                ("pull_request", models.JSONField(default=None, null=True)),
                ("workflow_run", models.JSONField(default=None, null=True)),
                ("workflow_job", models.JSONField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("webhooks.webhookreceived",),
        ),
    ]
