# Generated by Django 4.1.1 on 2022-09-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_githubwebhookreceived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="githubwebhookreceived",
            options={"ordering": ["-received_at"]},
        ),
        migrations.AlterModelOptions(
            name="webhookreceived",
            options={"ordering": ["-received_at"]},
        ),
    ]
