# Generated by Django 4.1.1 on 2022-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0005_githubpullrequest_githubworkflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="githubpullrequest",
            options={"ordering": ["-datetime_created"]},
        ),
        migrations.AlterModelOptions(
            name="githubworkflow",
            options={"ordering": ["-datetime_created"]},
        ),
        migrations.RemoveField(
            model_name="githubpullrequest",
            name="action",
        ),
        migrations.RemoveField(
            model_name="githubworkflow",
            name="title",
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="github_id",
            field=models.CharField(
                blank=True,
                help_text="The id of the workflow.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="github_user",
            field=models.CharField(
                blank=True, help_text="The user of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="github_user_link",
            field=models.CharField(
                blank=True,
                help_text="The user link of the PR.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="is_draft",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is the PR a draft?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="is_merged",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is the PR merged?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="pr_number",
            field=models.IntegerField(
                blank=True, help_text="The number of the PR.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="repository",
            field=models.CharField(
                blank=True,
                help_text="The repository of the PR.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="repository_link",
            field=models.CharField(
                blank=True,
                help_text="The repository link of the PR.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="state",
            field=models.CharField(
                blank=True, help_text="The state of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="title",
            field=models.CharField(
                blank=True, help_text="The title of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubworkflow",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="The action of the workflow.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubworkflow",
            name="conclusion",
            field=models.CharField(
                blank=True,
                help_text="The conclusion of the PR.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubworkflow",
            name="github_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the workflow.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubworkflow",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the workflow.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="githubworkflow",
            name="pull_request_github_id",
            field=models.CharField(
                blank=True, help_text="The ID of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubworkflow",
            name="status",
            field=models.CharField(
                blank=True, help_text="The status of the PR.", max_length=255, null=True
            ),
        ),
    ]
