# Generated by Django 4.1.1 on 2022-09-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0006_alter_githubpullrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubpullrequest",
            name="pull_request_url",
            field=models.CharField(
                blank=True, help_text="The link of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="githubworkflow",
            name="pull_request_url",
            field=models.CharField(
                blank=True, help_text="The URL of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="githubworkflow",
            name="workflow_url",
            field=models.CharField(
                blank=True,
                help_text="The URL of the workflow.",
                max_length=255,
                null=True,
            ),
        ),
    ]
