# Generated by Django 4.1.1 on 2022-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0007_githubpullrequest_pull_request_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubworkflow",
            name="github_user",
            field=models.CharField(
                blank=True, help_text="The user of the PR.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="githubworkflow",
            name="github_user_link",
            field=models.CharField(
                blank=True,
                help_text="The user link of the PR.",
                max_length=255,
                null=True,
            ),
        ),
    ]
