# Generated by Django 4.1.1 on 2022-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0008_githubworkflow_github_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubpullrequest",
            name="action",
            field=models.CharField(
                blank=True, help_text="The action of the PR.", max_length=255, null=True
            ),
        ),
    ]
